export const FETCH_MACHINE_LIST = 'FETCH_MACHINE_LIST';
export const FETCH_MACHINE_STATUS = 'FETCH_MACHINE_STATUS';
export const CREATE_MACHINE = 'CREATE_MACHINE';
export const REMOVE_MACHINE = 'REMOVE_MACHINE';
export const START_MACHINE = 'START_MACHINE';
export const STOP_MACHINE = 'STOP_MACHINE';
export const FETCH_MACHINE_IP = 'FETCH_MACHINE_IP';

export const SELECT_DRIVER = 'SELECT_DRIVER';

export const FETCH_DOCKER_INFO = 'FETCH_DOCKER_INFO';

// container
export const FETCH_MACHINE_CONTAINER_LIST = 'FETCH_MACHINE_CONTAINER_LIST';
export const INSPECT_MACHINE_CONTAINER = 'INSPECT_MACHINE_CONTAINER';
export const FETCH_MACHINE_CONTAINER_LOGS = 'FETCH_MACHINE_CONTAINER_LOGS';
export const CREATE_MACHINE_CONTAINER = 'CREATE_MACHINE_CONTAINER';
export const START_MACHINE_CONTAINER = 'START_MACHINE_CONTAINER';
export const STOP_MACHINE_CONTAINER = 'STOP_MACHINE_CONTAINER';
export const REMOVE_MACHINE_CONTAINER = 'REMOVE_MACHINE_CONTAINER';
export const PAUSE_MACHINE_CONTAINER = 'PAUSE_MACHINE_CONTAINER';
export const UNPAUSE_MACHINE_CONTAINER = 'UNPAUSE_MACHINE_CONTAINER';

export const FETCH_CONTAINER_LIST = 'FETCH_CONTAINER_LIST';
export const INSPECT_CONTAINER = 'INSPECT_CONTAINER';
export const FETCH_CONTAINER_LOGS = 'FETCH_CONTAINER_LOGS';
export const CREATE_CONTAINER = 'CREATE_CONTAINER';
export const START_CONTAINER = 'START_CONTAINER';
export const STOP_CONTAINER = 'STOP_CONTAINER';
export const REMOVE_CONTAINER = 'REMOVE_CONTAINER';
export const PAUSE_CONTAINER = 'PAUSE_CONTAINER';
export const UNPAUSE_CONTAINER = 'UNPAUSE_CONTAINER';

export const SET_SHOW_ALL_CONTAINERS = 'SET_SHOW_ALL_CONTAINERS';

//image
export const FETCH_MACHINE_IMAGE_LIST = 'FETCH_MACHINE_IMAGE_LIST';
export const PULL_MACHINE_IMAGE = 'PULL_MACHINE_IMAGE';
export const REMOVE_MACHINE_IMAGE = 'REMOVE_MACHINE_IMAGE';

export const FETCH_IMAGE_LIST = 'FETCH_IMAGE_LIST';
export const PULL_IMAGE = 'PULL_IMAGE';
export const REMOVE_IMAGE = 'REMOVE_IMAGE';

export const SET_SHOW_ALL_IMAGE = 'SET_SHOW_ALL_IMAGE';



export const SEARCH_REGISTRY_IMAGES = 'SEARCH_REGISTRY_IMAGES';

export const ABORT_HTTP_REQUEST = 'ABORT_HTTP_REQUEST';
export const ABORT_HTTP_REQUEST_COMPLETE = 'ABORT_HTTP_REQUEST_COMPLETE';
