export const FETCH_MACHINE_LIST = 'FETCH_MACHINE_LIST';
export const FETCH_MACHINE_STATUS = 'FETCH_MACHINE_STATUS';
export const CREATE_MACHINE = 'CREATE_MACHINE';
export const REMOVE_MACHINE = 'REMOVE_MACHINE';
export const START_MACHINE = 'START_MACHINE';
export const STOP_MACHINE = 'STOP_MACHINE';

export const SELECT_DRIVER = 'SELECT_DRIVER';

export const FETCH_DOCKER_INFO = 'FETCH_DOCKER_INFO';

export const FETCH_MACHINE_CONTAINER_LIST = 'FETCH_MACHINE_CONTAINER_LIST';
export const CREATE_MACHINE_CONTAINER = 'CREATE_MACHINE_CONTAINER';
export const SET_SHOW_ALL_CONTAINERS = 'SET_SHOW_ALL_CONTAINERS';

export const FETCH_MACHINE_IMAGE_LIST = 'FETCH_MACHINE_IMAGE_LIST';
export const CREATE_MACHINE_IMAGE = 'CREATE_MACHINE_IMAGE';
export const SET_SHOW_ALL_IMAGE = 'SET_SHOW_ALL_IMAGE';

export const SEARCH_REGISTRY_IMAGES = 'SEARCH_REGISTRY_IMAGES';
