export const FETCH_MACHINE_LIST = 'FETCH_MACHINE_LIST';
export const FETCH_MACHINE_STATUS = 'FETCH_MACHINE_STATUS';
export const CREATE_MACHINE = 'CREATE_MACHINE';
export const REMOVE_MACHINE = 'REMOVE_MACHINE';
export const START_MACHINE = 'START_MACHINE';
export const STOP_MACHINE = 'STOP_MACHINE';

export const SELECT_DRIVER = 'SELECT_DRIVER';

export const FETCH_DOCKER_INFO = 'FETCH_DOCKER_INFO';
